os: linux
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  FLASK_APP: project/__init__.py
  FLASK_ENV: development
  APP_SETTINGS: project.config.DevelopmentConfig
  DATABASE_TEST_URL: postgresql://username:password@host:5432/database

before_install:
  - python --version

install:
  - pip install -r requirements-dev.txt

before_script:
  - gunicorn -b 0.0.0.0:5000 manage:app --daemon

script:
  - echo "Test ok!"
  # - python -m pytest "project/tests"

after_success:
  - echo "Test ok, exit"